version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - .env.prod.db

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - media_volume:/app/media
    env_file:
      - .env.prod
    depends_on:
      - redis
      - db
    command: celery -A shaboom worker -l info

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    depends_on:
      - redis
      - db
    command: celery -A shaboom beat -l info

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
  redis_data:
