version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shaboom_dev
      - POSTGRES_USER=shaboom_user
      - POSTGRES_PASSWORD=shaboom_pass

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - media_volume:/app/media
    env_file:
      - .env.dev
    depends_on:
      - redis
      - db
    command: celery -A shaboom worker -l info

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - redis
      - db
    command: celery -A shaboom beat -l info

volumes:
  postgres_data:
  media_volume:
